[package]
name = "day-4-part-2"
version = "0.1.0"
authors = ["Oliver Wright <meiamsome@meiamso.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
